site_name: Tour of WGSL
site_url: https://webmaven.github.io/tour-of-wgsl/
repo_url: https://github.com/webmaven/tour-of-wgsl
repo_name: webmaven/tour-of-wgsl

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.sections
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search

hooks:
  - hooks/wgsl_tour.py

extra_css:
  - assets/css/app.css

extra_javascript:
  - path: assets/js/app.js
    type: module
